# Generated by Django 4.2.27 on 2026-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories_photos/', verbose_name='Фото'),
        ),
    ]
